[2023-03-19T21:49:31.311+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_spark_processing.process_data scheduled__2023-03-18T00:00:00+00:00 [queued]>
[2023-03-19T21:49:31.335+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_spark_processing.process_data scheduled__2023-03-18T00:00:00+00:00 [queued]>
[2023-03-19T21:49:31.336+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-19T21:49:31.337+0000] {taskinstance.py:1283} INFO - Starting attempt 9 of 10
[2023-03-19T21:49:31.337+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-19T21:49:31.377+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocSubmitJobOperator): process_data> on 2023-03-18 00:00:00+00:00
[2023-03-19T21:49:31.394+0000] {standard_task_runner.py:55} INFO - Started process 20667 to run task
[2023-03-19T21:49:31.405+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_spark_processing', 'process_data', 'scheduled__2023-03-18T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/p_submit_job_draft.py', '--cfg-path', '/tmp/tmphb2yqy04']
[2023-03-19T21:49:31.415+0000] {standard_task_runner.py:83} INFO - Job 154: Subtask process_data
[2023-03-19T21:49:31.493+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-19T21:49:31.586+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-19T21:49:31.663+0000] {task_command.py:388} INFO - Running <TaskInstance: project_spark_processing.process_data scheduled__2023-03-18T00:00:00+00:00 [running]> on host 50ce40c43c89
[2023-03-19T21:49:31.894+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_spark_processing
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-18T00:00:00+00:00
[2023-03-19T21:49:31.896+0000] {dataproc.py:1985} INFO - Submitting job
[2023-03-19T21:49:31.898+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-19T21:49:31.898+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-19T21:49:32.228+0000] {dataproc.py:1997} INFO - Job your_job_id2 submitted successfully.
[2023-03-19T21:49:32.257+0000] {dataproc.py:2017} INFO - Waiting for job your_job_id2 to complete
[2023-03-19T21:50:02.535+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2019, in execute
    job_id=new_job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 723, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "dtc-de-course-375420"
  job_id: "your_job_id2"
}
placement {
  cluster_name: "my-dataproc-cluster"
  cluster_uuid: "245a5280-f4b3-49c8-a701-e9c7026df1c0"
}
pyspark_job {
  main_python_file_uri: "gs://dtc_data_lake_dtc-de-course-375420/spark_job.py"
  args: "--input_table"
  args: "dtc-de-course-375420.chicago_crime_all.et_chicago_crimes_lite"
}
status {
  state: ERROR
  details: "Job failed with message [AttributeError: \'Namespace\' object has no attribute \'param1\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/your_job_id2?project=dtc-de-course-375420&region=europe-west6\ngcloud dataproc jobs wait \'your_job_id2\' --region \'europe-west6\' --project \'dtc-de-course-375420\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/\ngs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/driveroutput"
  state_start_time {
    seconds: 1679262599
    nanos: 309160000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1679262572
    nanos: 212266000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1679262572
    nanos: 257131000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1679262572
    nanos: 753766000
  }
}
driver_control_files_uri: "gs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/"
driver_output_resource_uri: "gs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/driveroutput"
job_uuid: "b27281c5-cbf9-41d4-963c-5339634b2ba8"
done: true

[2023-03-19T21:50:02.550+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=project_spark_processing, task_id=process_data, execution_date=20230318T000000, start_date=20230319T214931, end_date=20230319T215002
[2023-03-19T21:50:02.580+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 154 for task process_data (Job failed:
reference {
  project_id: "dtc-de-course-375420"
  job_id: "your_job_id2"
}
placement {
  cluster_name: "my-dataproc-cluster"
  cluster_uuid: "245a5280-f4b3-49c8-a701-e9c7026df1c0"
}
pyspark_job {
  main_python_file_uri: "gs://dtc_data_lake_dtc-de-course-375420/spark_job.py"
  args: "--input_table"
  args: "dtc-de-course-375420.chicago_crime_all.et_chicago_crimes_lite"
}
status {
  state: ERROR
  details: "Job failed with message [AttributeError: \'Namespace\' object has no attribute \'param1\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/your_job_id2?project=dtc-de-course-375420&region=europe-west6\ngcloud dataproc jobs wait \'your_job_id2\' --region \'europe-west6\' --project \'dtc-de-course-375420\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/\ngs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/driveroutput"
  state_start_time {
    seconds: 1679262599
    nanos: 309160000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1679262572
    nanos: 212266000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1679262572
    nanos: 257131000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1679262572
    nanos: 753766000
  }
}
driver_control_files_uri: "gs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/"
driver_output_resource_uri: "gs://dataproc-staging-europe-west6-192108012555-yegdrxcc/google-cloud-dataproc-metainfo/245a5280-f4b3-49c8-a701-e9c7026df1c0/jobs/your_job_id2/driveroutput"
job_uuid: "b27281c5-cbf9-41d4-963c-5339634b2ba8"
done: true
; 20667)
[2023-03-19T21:50:02.615+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-19T21:50:02.652+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
