[2023-03-15T19:51:16.784+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_gcs_to_bq.gcs_to_bq scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2023-03-15T19:51:16.799+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_gcs_to_bq.gcs_to_bq scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2023-03-15T19:51:16.799+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:51:16.799+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-15T19:51:16.799+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:51:16.820+0000] {taskinstance.py:1303} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq> on 2023-03-14 00:00:00+00:00
[2023-03-15T19:51:16.830+0000] {standard_task_runner.py:55} INFO - Started process 6236 to run task
[2023-03-15T19:51:16.836+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_gcs_to_bq', 'gcs_to_bq', 'scheduled__2023-03-14T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/p_gcs_to_bq.py', '--cfg-path', '/tmp/tmp51n__5a3']
[2023-03-15T19:51:16.840+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask gcs_to_bq
[2023-03-15T19:51:16.863+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-15T19:51:16.898+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-15T19:51:16.949+0000] {task_command.py:388} INFO - Running <TaskInstance: project_gcs_to_bq.gcs_to_bq scheduled__2023-03-14T00:00:00+00:00 [running]> on host 8d6d3f05a6c2
[2023-03-15T19:51:17.063+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_gcs_to_bq
AIRFLOW_CTX_TASK_ID=gcs_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-14T00:00:00+00:00
[2023-03-15T19:51:17.066+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-15T19:51:17.067+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-15T19:51:17.068+0000] {gcs_to_bigquery.py:382} INFO - Using existing BigQuery table for storing data...
[2023-03-15T19:51:17.123+0000] {gcs_to_bigquery.py:386} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dtc-de-course-375420', 'datasetId': 'chicago_crime_all', 'tableId': 'my_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://dtc_data_lake_dtc-de-course-375420/project/*.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'ID', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'Case Number', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'index', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'Date', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Block', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'IUCR', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Primary Type', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Description', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Location Description', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Arrest', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'Domestic', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'Beat', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'District', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Ward', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Community Area', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'FBI Code', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'X Coordinate', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Y Coordinate', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Year', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'Updated On', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Latitude', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Longitude', 'type': 'number', 'mode': 'NULLABLE'}, {'name': 'Location', 'type': 'STRING', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-03-15T19:51:17.125+0000] {bigquery.py:1546} INFO - Inserting job ***_project_gcs_to_bq_gcs_to_bq_2023_03_14T00_00_00_00_00_7d58acd97493b6e2eeb8bcb48b0b7aa2
[2023-03-15T19:51:17.253+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 387, in execute
    job = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 314, in _submit_job
    nowait=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1549, in insert_job
    job._begin()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 518, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-375420/jobs?prettyPrint=false: Invalid value for type: NUMBER is not a valid value
[2023-03-15T19:51:17.272+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=project_gcs_to_bq, task_id=gcs_to_bq, execution_date=20230314T000000, start_date=20230315T195116, end_date=20230315T195117
[2023-03-15T19:51:17.291+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task gcs_to_bq (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/dtc-de-course-375420/jobs?prettyPrint=false: Invalid value for type: NUMBER is not a valid value; 6236)
[2023-03-15T19:51:17.331+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-15T19:51:17.359+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
