[2023-03-20T16:29:59.745+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_spark_processing.process_data scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20T16:29:59.759+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_spark_processing.process_data scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20T16:29:59.759+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T16:29:59.759+0000] {taskinstance.py:1283} INFO - Starting attempt 13 of 14
[2023-03-20T16:29:59.759+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T16:29:59.779+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocSubmitJobOperator): process_data> on 2023-03-19 00:00:00+00:00
[2023-03-20T16:29:59.788+0000] {standard_task_runner.py:55} INFO - Started process 7232 to run task
[2023-03-20T16:29:59.796+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_spark_processing', 'process_data', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/p_submit_job_draft.py', '--cfg-path', '/tmp/tmpo_fxb_pm']
[2023-03-20T16:29:59.799+0000] {standard_task_runner.py:83} INFO - Job 203: Subtask process_data
[2023-03-20T16:29:59.820+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T16:29:59.852+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-20T16:29:59.894+0000] {task_command.py:388} INFO - Running <TaskInstance: project_spark_processing.process_data scheduled__2023-03-19T00:00:00+00:00 [running]> on host 4fd00a82f4e9
[2023-03-20T16:30:00.003+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_spark_processing
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=13
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-20T16:30:00.005+0000] {dataproc.py:1985} INFO - Submitting job
[2023-03-20T16:30:00.007+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-03-20T16:30:00.007+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-20T16:30:00.071+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1994, in execute
    metadata=self.metadata,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 794, in submit_job
    metadata=metadata,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/dataproc_v1/services/job_controller/client.py", line 494, in submit_job
    request = jobs.SubmitJobRequest(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/proto/message.py", line 516, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/proto/marshal/marshal.py", line 211, in to_proto
    pb_value = rule.to_proto(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/proto/marshal/rules/message.py", line 36, in to_proto
    return self._descriptor(**value)
ValueError: Protocol message PySparkJob has no "dataproc_jars" field.
[2023-03-20T16:30:00.086+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=project_spark_processing, task_id=process_data, execution_date=20230319T000000, start_date=20230320T162959, end_date=20230320T163000
[2023-03-20T16:30:00.104+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 203 for task process_data (Protocol message PySparkJob has no "dataproc_jars" field.; 7232)
[2023-03-20T16:30:00.128+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T16:30:00.155+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
