[2023-03-20T20:52:21.460+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T20:52:21.481+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T20:52:21.481+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T20:52:21.482+0000] {taskinstance.py:1283} INFO - Starting attempt 5 of 5
[2023-03-20T20:52:21.483+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T20:52:21.521+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryExecuteQueryOperator): execute_sql_file> on 2023-03-20 20:40:54.242399+00:00
[2023-03-20T20:52:21.538+0000] {standard_task_runner.py:55} INFO - Started process 3684 to run task
[2023-03-20T20:52:21.567+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_bigquery_sql_dag', 'execute_sql_file', 'manual__2023-03-20T20:40:54.242399+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/project_bq_partitioning.py', '--cfg-path', '/tmp/tmpr8jv8go2']
[2023-03-20T20:52:21.582+0000] {standard_task_runner.py:83} INFO - Job 232: Subtask execute_sql_file
[2023-03-20T20:52:21.628+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T20:52:21.771+0000] {task_command.py:388} INFO - Running <TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [running]> on host 71cf0a128c31
[2023-03-20T20:52:21.853+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'execute_sql_file', field 'sql'. Template: '/home/subin/project_master/scripts/bq_partitioning.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/subin/project_master/scripts/bq_partitioning.sql
[2023-03-20T20:52:21.856+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/subin/project_master/scripts/bq_partitioning.sql
[2023-03-20T20:52:21.875+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=project_bigquery_sql_dag, task_id=execute_sql_file, execution_date=20230320T204054, start_date=20230320T205221, end_date=20230320T205221
[2023-03-20T20:52:21.902+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 232 for task execute_sql_file (/home/subin/project_master/scripts/bq_partitioning.sql; 3684)
[2023-03-20T20:52:21.926+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T20:52:21.969+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
