[2023-03-20T23:00:54.533+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T23:00:54.572+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T23:00:54.572+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T23:00:54.572+0000] {taskinstance.py:1283} INFO - Starting attempt 19 of 20
[2023-03-20T23:00:54.573+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T23:00:54.633+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryInsertJobOperator): execute_sql_file> on 2023-03-20 20:40:54.242399+00:00
[2023-03-20T23:00:54.644+0000] {standard_task_runner.py:55} INFO - Started process 1385 to run task
[2023-03-20T23:00:54.667+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_bigquery_sql_dag', 'execute_sql_file', 'manual__2023-03-20T20:40:54.242399+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/project_bq_partitioning.py', '--cfg-path', '/tmp/tmpa52yqnhq']
[2023-03-20T23:00:54.684+0000] {standard_task_runner.py:83} INFO - Job 247: Subtask execute_sql_file
[2023-03-20T23:00:54.729+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T23:00:54.908+0000] {task_command.py:388} INFO - Running <TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [running]> on host 796cac132c25
[2023-03-20T23:00:55.408+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_bigquery_sql_dag
AIRFLOW_CTX_TASK_ID=execute_sql_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T20:40:54.242399+00:00
AIRFLOW_CTX_TRY_NUMBER=19
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T20:40:54.242399+00:00
[2023-03-20T23:00:55.412+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-20T23:00:55.415+0000] {bigquery.py:2731} INFO - Executing: {'query': {'query': 'CREATE OR REPLACE TABLE `dtc-de-course-375420.chicago_crime_all.ET_CHICAGO_CRIMES_DATEFORMATTED` AS\nSELECT\n  DATE(PARSE_DATETIME("%m/%d/%Y %I:%M:%S %p", date)) AS New_Date,*\nFROM\n  `dtc-de-course-375420.chicago_crime_all.et_chicago_crimes`;\n  \n  \nCREATE OR REPLACE TABLE `dtc-de-course-375420.chicago_crime_all.CHICAGO_CRIMES_PARTITIONED`\nPARTITION BY New_Date\nAS\nSELECT * FROM `dtc-de-course-375420.chicago_crime_all.ET_CHICAGO_CRIMES_DATEFORMATTED`;', 'useLegacySql': False}}'
[2023-03-20T23:00:55.691+0000] {bigquery.py:1546} INFO - Inserting job ***_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_258c48c01aefb2263bfa82001988c4db
[2023-03-20T23:01:03.901+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2782, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Query error: Too many partitions produced by query, allowed 4000, query produces at least 7959 partitions at [8:1]

Location: europe-west6
Job ID: airflow_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_258c48c01aefb2263bfa82001988c4db

[2023-03-20T23:01:03.924+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=project_bigquery_sql_dag, task_id=execute_sql_file, execution_date=20230320T204054, start_date=20230320T230054, end_date=20230320T230103
[2023-03-20T23:01:03.955+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 247 for task execute_sql_file (400 Query error: Too many partitions produced by query, allowed 4000, query produces at least 7959 partitions at [8:1]

Location: europe-west6
Job ID: airflow_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_258c48c01aefb2263bfa82001988c4db
; 1385)
[2023-03-20T23:01:03.994+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T23:01:04.036+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
