[2023-03-20T22:23:00.351+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T22:23:00.369+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T22:23:00.370+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T22:23:00.370+0000] {taskinstance.py:1283} INFO - Starting attempt 9 of 10
[2023-03-20T22:23:00.370+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T22:23:00.406+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryExecuteQueryOperator): execute_sql_file> on 2023-03-20 20:40:54.242399+00:00
[2023-03-20T22:23:00.423+0000] {standard_task_runner.py:55} INFO - Started process 7373 to run task
[2023-03-20T22:23:00.435+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_bigquery_sql_dag', 'execute_sql_file', 'manual__2023-03-20T20:40:54.242399+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/project_bq_partitioning.py', '--cfg-path', '/tmp/tmp0gmxfclx']
[2023-03-20T22:23:00.444+0000] {standard_task_runner.py:83} INFO - Job 236: Subtask execute_sql_file
[2023-03-20T22:23:00.480+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T22:23:00.629+0000] {task_command.py:388} INFO - Running <TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [running]> on host 71cf0a128c31
[2023-03-20T22:23:00.735+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'execute_sql_file', field 'sql'. Template: '/opt/***/scripts/bq_partitioning.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/scripts/bq_partitioning.sql
[2023-03-20T22:23:00.755+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/scripts/bq_partitioning.sql
[2023-03-20T22:23:00.805+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=project_bigquery_sql_dag, task_id=execute_sql_file, execution_date=20230320T204054, start_date=20230320T222300, end_date=20230320T222300
[2023-03-20T22:23:00.837+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 236 for task execute_sql_file (/opt/airflow/scripts/bq_partitioning.sql; 7373)
[2023-03-20T22:23:00.889+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T22:23:00.980+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
