[2023-03-20T23:06:08.945+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T23:06:08.983+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [queued]>
[2023-03-20T23:06:08.984+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T23:06:08.984+0000] {taskinstance.py:1283} INFO - Starting attempt 20 of 20
[2023-03-20T23:06:08.985+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T23:06:09.041+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryInsertJobOperator): execute_sql_file> on 2023-03-20 20:40:54.242399+00:00
[2023-03-20T23:06:09.061+0000] {standard_task_runner.py:55} INFO - Started process 1600 to run task
[2023-03-20T23:06:09.083+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_bigquery_sql_dag', 'execute_sql_file', 'manual__2023-03-20T20:40:54.242399+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/project_bq_partitioning.py', '--cfg-path', '/tmp/tmp4ziu8wzh']
[2023-03-20T23:06:09.096+0000] {standard_task_runner.py:83} INFO - Job 248: Subtask execute_sql_file
[2023-03-20T23:06:09.160+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T23:06:09.403+0000] {task_command.py:388} INFO - Running <TaskInstance: project_bigquery_sql_dag.execute_sql_file manual__2023-03-20T20:40:54.242399+00:00 [running]> on host 796cac132c25
[2023-03-20T23:06:09.842+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_bigquery_sql_dag
AIRFLOW_CTX_TASK_ID=execute_sql_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T20:40:54.242399+00:00
AIRFLOW_CTX_TRY_NUMBER=20
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T20:40:54.242399+00:00
[2023-03-20T23:06:09.844+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-20T23:06:09.858+0000] {bigquery.py:2731} INFO - Executing: {'query': {'query': 'CREATE OR REPLACE TABLE `dtc-de-course-375420.chicago_crime_all.ET_CHICAGO_CRIMES_DATEFORMATTED` AS\nSELECT\n  DATE(PARSE_DATETIME("%m/%d/%Y %I:%M:%S %p", date)) AS New_Date,*\nFROM\n  `dtc-de-course-375420.chicago_crime_all.et_chicago_crimes`;\n  \n  \nCREATE OR REPLACE TABLE `dtc-de-course-375420.chicago_crime_all.CHICAGO_CRIMES_PARTITIONED`\nPARTITION BY New_Date\nAS\nSELECT * FROM `dtc-de-course-375420.chicago_crime_all.ET_CHICAGO_CRIMES_DATEFORMATTED`;', 'useLegacySql': False}}'
[2023-03-20T23:06:10.148+0000] {bigquery.py:1546} INFO - Inserting job ***_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_6ea00b3fd05a2490dd78d9b26b1d3cd5
[2023-03-20T23:06:17.978+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2782, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Query error: Too many partitions produced by query, allowed 4000, query produces at least 7959 partitions at [8:1]

Location: europe-west6
Job ID: airflow_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_6ea00b3fd05a2490dd78d9b26b1d3cd5

[2023-03-20T23:06:17.999+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=project_bigquery_sql_dag, task_id=execute_sql_file, execution_date=20230320T204054, start_date=20230320T230608, end_date=20230320T230617
[2023-03-20T23:06:18.029+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 248 for task execute_sql_file (400 Query error: Too many partitions produced by query, allowed 4000, query produces at least 7959 partitions at [8:1]

Location: europe-west6
Job ID: airflow_project_bigquery_sql_dag_execute_sql_file_2023_03_20T20_40_54_242399_00_00_6ea00b3fd05a2490dd78d9b26b1d3cd5
; 1600)
[2023-03-20T23:06:18.083+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T23:06:18.123+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
